"use client";

import { useEffect, useState, useCallback } from "react";
import ApprovalCard from "@/components/approvals/ApprovalCard";

const API_BASE = "http://localhost:3001";

export default function ApprovalsPage() {
  const [approvals, setApprovals] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);

  const fetchApprovals = useCallback(async () => {
    setIsRefreshing(true);
    try {
      const res = await fetch(`${API_BASE}/api/approvals?status=pending`);
      if (res.ok) {
        const data = await res.json();
        setApprovals(data.data || []);
      }
    } catch (err) {
      console.error("Failed to fetch approvals", err);
    } finally {
      setLoading(false);
      setIsRefreshing(false);
    }
  }, []);

  useEffect(() => {
    fetchApprovals();
  }, [fetchApprovals]);

  const handleDecision = async (id: string, decision: "approved" | "rejected") => {
    try {
      await fetch(`${API_BASE}/api/approvals/${id}/decision`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: decision, approved_by: "Human", feedback: "" })
      });
      setApprovals(current => current.filter(a => a.id !== id));
    } catch (err) {
      console.error(`Failed to ${decision} approval ${id}`, err);
    }
  };

  return (
    <div className="space-y-10 animate-in fade-in slide-in-from-bottom-4 duration-700 ease-out">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 glass-card p-8 rounded-[2rem] relative overflow-hidden">
         <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/10 rounded-full blur-[80px] -z-10 translate-x-1/2 -translate-y-1/2"></div>
         <div>
            <h1 className="text-4xl font-extrabold tracking-tight text-foreground mb-3 flex items-center gap-3">
               Approvals Queue
               {approvals.length > 0 && (
                  <span className="px-3 py-1 text-xs font-bold bg-accent/20 text-accent rounded-full border border-accent/50 shadow-[0_0_15px_rgba(236,72,153,0.5)]">
                     {approvals.length} Pending
                  </span>
               )}
            </h1>
            <p className="text-muted-foreground text-lg">Review and authorize execution proposals generated by autonomous agents.</p>
         </div>
         <button 
           onClick={fetchApprovals}
           disabled={isRefreshing}
           className="p-3 rounded-2xl bg-white/5 text-foreground hover:bg-white/10 transition-all border border-white/10 group shadow-lg"
           title="Sync Approvals"
         >
           <svg className={`w-6 h-6 text-muted-foreground group-hover:text-primary transition-colors ${isRefreshing ? "animate-spin text-primary" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
             <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
           </svg>
         </button>
      </div>

      {loading && approvals.length === 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-pulse">
           {[1, 2, 3].map(i => <div key={i} className="h-48 glass-panel rounded-2xl opacity-50"></div>)}
        </div>
      ) : approvals.length === 0 ? (
        <div className="glass-panel p-20 text-center rounded-[2rem] border-white/5 shadow-2xl">
           <div className="w-20 h-20 mx-auto bg-emerald-500/10 text-emerald-500 rounded-full flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(16,185,129,0.2)]">
             <svg className="w-10 h-10" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
           </div>
           <h3 className="text-2xl font-bold mb-3 text-foreground tracking-tight">All caught up!</h3>
           <p className="text-muted-foreground text-lg max-w-md mx-auto">There are no pending execution proposals requiring human-in-the-loop authorization right now.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {approvals.map(approval => (
             <ApprovalCard 
               key={approval.id} 
               approval={approval} 
               onDecision={handleDecision} 
             />
          ))}
        </div>
      )}
    </div>
  );
}
